config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}
                                    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, shallow: true
    resources :likes, only: [:create], likeable_type: "Post"
  end

  resources :likes, only: [:destroy]

  resources :comments, only: [:edit, :update, :destroy]
  resources :users, only: [:show, :index]
  resources :friend_requests, only: [:index, :create, :update]
  resources :friends, controller: :friendships, only: [:index] #show friends list
  
  resources :pokes, only: [:create]

  resources :notifications, only: [:index, :update]
  resource :profile, only: [:edit, :update]
  resolve('Profile') { [:profile] }

  get '/privacy-policy', controller: :privacy_policy, action: :show
  root to: "posts#index"
end

app/views/shared/_user_panel.html.erb
<div class="panel is-info">
        <div class="panel-heading profile-panel">
                <div class="image is-128x128 profile-panel-image">
                    <% img_src = current_user.profile.avatar.attached? ? url_for(current_user.profile.avatar.variant(resize_to_fill: [128, 128])) : "http://via.placeholder.com/128" %>
                    <img src=<%= img_src %> alt="" class="is-rounded">
                </div>

                <div class="content has-text-centered">
                    <p class="title is-5 has-text-white"><%= "#{current_user.profile.firstname} #{current_user.profile.lastname}"%></p>
                </div>
        </div>

        
        <%= link_to posts_path, class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-home"></i>
            </span>
            Timeline
        <% end %>
        

        
        <%= link_to user_path(current_user), class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-user-circle"></i>
            </span>
            My Profile
        <% end %>
    

        
        <%= link_to friends_path, class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-user-friends"></i>
            </span>
            Friends
        <% end %>
        

        
        <%= link_to notifications_path, class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-bell"></i>
            </span>
            Notifications
        <% end %>
        

        
        <%= link_to friend_requests_path, class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-envelope"></i>
            </span>
            Pending Friend Requests
        <% end %>
        

        
        <%= link_to users_path, class: "panel-block" do %>
            <span class="panel-icon">
                <i class="fas fa-users"></i>
            </span>
            Add Friends
        <% end %>

        <%= link_to user_registration_path, class: "panel-block", data: {confirm: "Are you sure you want to delete your account?"}, method: :delete do %>
            <span class="panel-icon">
                <i class="fas fa-user-slash"></i>
            </span>
            Delete account
        <% end %>
    </div>