config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}
                                    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, shallow: true
    resources :likes, only: [:create], likeable_type: "Post"
  end

  resources :likes, only: [:destroy]

  resources :comments, only: [:edit, :update, :destroy]
  resources :users, only: [:show, :index]
  resources :friend_requests, only: [:index, :create, :update]
  resources :friends, controller: :friendships, only: [:index] #show friends list
  
  resources :pokes, only: [:create]

  resources :notifications, only: [:index, :update]
  resource :profile, only: [:edit, :update]
  resolve('Profile') { [:profile] }

  get '/privacy-policy', controller: :privacy_policy, action: :show
  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, as: :likeable, dependent: :destroy
    has_one_attached :image

    validates :body, presence: true, unless: Proc.new { |p| p.image.attached? }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.where(user_id: current_user.friends.ids).order(created_at: :desc)
        @post = Post.new
    end

    def show 
        @post = Post.find_by(id: params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)

        if attachment_is_not_image
            flash[:alert] = "Attachment must be an image"
        elsif @post.save
            flash[:notice] = "Successfully created post"
            redirect_to @post 
            return
        else
            flash.now[:alert] = "Unable to create post"
        end

        redirect_back fallback_location: 'new'
    end

    def edit
        begin
            @post = current_user.posts.find_by!(id: params[:id])
        rescue
            if Post.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to edit that post."
            else
                flash[:alert] = "Post does not exist."
            end
            redirect_to action: 'index'
        end
    end

    def update
        begin
            @post = current_user.posts.find_by!(id: params[:id])
        rescue 
            if Post.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to edit that post."
            else
                flash[:alert] = "Post does not exist."
            end
            redirect_to action: 'index'
        end

        if attachment_is_not_image
            flash.now[:alert] = "Attachment must be an image"
        elsif @post.update(post_params)
            flash[:notice] = "Successfully updated post!"
            redirect_to @post
            return
        else
            flash.now[:alert] = "Unable to update post"
        end

        render 'edit'
    end

    def destroy
        begin
            @post = current_user.posts.find_by!(id: params[:id])
        rescue 
            if Post.find_by(id: params[:id])
                flash[:alert] = "You don't have permission to delete that post."
            else
                flash[:alert] = "Post does not exist."
            end
            redirect_to action: 'index'
        end

        @post.destroy
        flash[:notice] = "Post successfully deleted"
        redirect_to action: 'index'
    end

    private
    def post_params
        params.require(:post).permit(:body, :image)
    end

    private
    def attachment_is_not_image
        post_params[:image] && !post_params[:image].content_type.start_with?("image")
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% post_form_label ||= "Post something"
   post_form_submit ||= "Share"
%>

<%= form_with model: post do |f| %>
        <div class="field">
            <%= f.label :body, post_form_label, class: "label" %>
            <div class="control">
                <%= f.text_area :body, class: "textarea has-fixed-size", rows: 5, placeholder: "Share your thoughts" %>
            </div>
        </div>

        <div class="field">
            <%= f.label :image, "Upload an image", class: "label" %>
            <div class="control">
                <%= f.file_field :image, class: "input" %>
            </div>
        </div>
        <%= f.submit post_form_submit, class:"button is-info" %>
<% end %>

app/views/posts/_post.html.erb
<div class="box">
    <%= render 'users/user_media_label', user: post.user, media: post do |section| %>
        <% if user_signed_in? && current_user == post.user %>
            <div class="level-right">
                <div class="level-item">
                    <%= link_to edit_post_path(post) do %>
                        <i class="fas fa-edit"></i>
                    <% end %>
                </div>
                <div class="level-item">
                    <%= link_to post_path(post), method: :delete do %>
                        <i class="fas fa-trash"></i>
                    <% end %>
                </div>
            </div>
        <% end %>
    <% end %>
    
    <div class="content">
    <% if post.body %>
        <p>
            <%= post.body %>
        </p>
        
    <% end %>
    <% if post.image.attached? %>
        <figure class="image">
            <%= image_tag(post.image) %>
        </figure>
    <% end %>
    </div>
    <hr />
    <div class="level">
        <div class="level-left">
            <p class="heading">
                <%= "#{post.likes.count} #{post.likes.count != 1 ? "likes" : "like" }" %>
            </p>
        </div>
        <div class="level-right">
            <p class="heading">
                <%= "#{post.comments.count} #{post.comments.count != 1 ? "comments" : "comment"}" %>
            </p>
        </div>
    </div>
    <div class="level">
    <div class="level-item">
        <% if post_like = current_user.likes.find_by(likeable_id: post.id) %>
            <%= link_to like_path(post_like.id), method: :delete do %>
                Unlike
            <% end %>
        <% else %>
            <%= link_to post_likes_path(post.id), method: :post do %>
                Like
            <% end %>
        <% end %>
    </div>
    <div class="level-item">
        <%= link_to new_post_comment_path(post) do %>
            Comment
        <% end %>
    </div>
    </div>
    
    <% post.comments.each do |comment| %>

        <div class="media">
            <figure class="media-left">
                <div class="image is-64x64">
                    <% c_img_src = comment.user.profile.avatar.attached? ? url_for(comment.user.profile.avatar.variant(resize_to_fill: [64, 64])) : "https://via.placeholder.com/64" %>
                    <img src=<%= c_img_src %> alt="" class="is-rounded">
                </div>
            </figure>
            <div class="media-content">
                <p class="title is-6">
                <%= link_to user_path(comment.user) do %>
                    <%= comment.user.profile.firstname %> <%= comment.user.profile.lastname %>
                <% end %>
                </p>
                <div class="content">
                    <%= comment.body %>
                </div>
            </div>
            <% if comment.user == current_user %>
                <div class="media-right">
                    <%= link_to edit_comment_path(comment) do %>
                        <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to comment_path(comment), method: :delete do %>
                        <i class="fas fa-trash"></i>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/posts/edit.html.erb
<section class="section">
<div class="columns">
<div class="column is-half is-offset-one-quarter">
<div class="box">
<%= render 'form', post: @post, post_form_label: "Edit Post", post_form_submit: "Save Post" %>
</div>
</div>
</div>
</section>

app/views/posts/index.html.erb
<section class="section">
<div class="columns">

<div class="column is-one-quarter">
    <%= render 'shared/user_panel' %>
</div>

<div class="column is-half">

<div class="box">
    <%= render 'form', post: @post %>
</div>


<% @posts.each do |post| %>
    <%= render 'post', post: post %>
<% end %>

</div>

</div>
</section>

app/views/posts/new.html.erb
<section class="section">
    <div class="columns">
        <div class="column is-half is-offset-one-quarter">
            <h2 class="title is-3">New Post</h2>
            <div class="box">
                <%= render 'form', post: @post %>
            </div>   
        </div>
    </div>
</section>

app/views/posts/show.html.erb
<section class="section">
    <div class="columns">

        <div class="column is-one-quarter">
            <%= render 'shared/user_panel' %>
        </div>

        <div class="column is-half">
            <%= render 'post', post: @post %>
        </div>
    </div>
</section>